name: Redhat ubi8

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Environment Preparation
        uses: actions/checkout@v3

      - name: Build and run docker container
        run: |
          docker build --file test/docker/Dockerfile_redhat_ubi8 --tag redhat_ubi8-image .
          docker run --rm redhat_ubi8-image

