name: Redhat ubi8

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Environment Preparation
        uses: actions/checkout@v3

      - name: Build and run Docker container for ZSH
        run: |
          DOCKER_BUILDKIT=1 docker build --file test/docker/Dockerfile_redhat_ubi8 --tag redhat_ubi8-image .
          docker run -e SELECTED_SHELL="zsh" --rm redhat_ubi8-image

      - name: Build and run Docker container for BASH
        run: |
          docker run -e SELECTED_SHELL="bash" --rm redhat_ubi8-image
