name: Shellcheck

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Environment Preparation
        uses: actions/checkout@v3

      - name: Run shellcheck script
        run : |
          apt-get update && apt-get install -y --no-install-recommends shellcheck
          test/test_shellcheck.sh -p
