name: Ubuntu latest

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Environment Preparation
        uses: actions/checkout@v3

      - name: Build and run Docker container
        run: |
          docker build -f test/docker/Dockerfile_ubuntu_latest -t ubuntu_latest-image .
          docker run --rm ubuntu_latest-image
