name: Ubuntu latest

on:
  push:
    branches:
      - '**'   # Matches all branches on push
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and run Docker container
      run: |
        docker build -f test/docker/Dockerfile_ubuntu_latest -t ubuntu_latest-image .
        docker run --rm ubuntu_latest-image
